// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5ekwD5Gm0ZJWtQzfc2IUataHUOrKQ_1c',
    appId: '1:881698898449:web:39b1834765b9ec2c0927b0',
    messagingSenderId: '881698898449',
    projectId: 'angiapp',
    authDomain: 'angiapp.firebaseapp.com',
    storageBucket: 'angiapp.firebasestorage.app',
    measurementId: 'G-43CC3LF5YF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtmMgNzVJ8EcJ3Dvl13i6FNxxA0tXXvrc',
    appId: '1:881698898449:android:e4138b1f367090650927b0',
    messagingSenderId: '881698898449',
    projectId: 'angiapp',
    storageBucket: 'angiapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgFGHvrFuXB92EqD4UdLg9zg0DXkqRb5M',
    appId: '1:881698898449:ios:5605fa0e2e3f4ce00927b0',
    messagingSenderId: '881698898449',
    projectId: 'angiapp',
    storageBucket: 'angiapp.firebasestorage.app',
    iosBundleId: 'com.fmstudio.anGi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgFGHvrFuXB92EqD4UdLg9zg0DXkqRb5M',
    appId: '1:881698898449:ios:5605fa0e2e3f4ce00927b0',
    messagingSenderId: '881698898449',
    projectId: 'angiapp',
    storageBucket: 'angiapp.firebasestorage.app',
    iosBundleId: 'com.fmstudio.anGi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5ekwD5Gm0ZJWtQzfc2IUataHUOrKQ_1c',
    appId: '1:881698898449:web:e2820512f05027890927b0',
    messagingSenderId: '881698898449',
    projectId: 'angiapp',
    authDomain: 'angiapp.firebaseapp.com',
    storageBucket: 'angiapp.firebasestorage.app',
    measurementId: 'G-ZRM4Z4BCPE',
  );
}
